In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10
from csv import writer
import pandas as pd

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import ticker as ticker

In [2]:
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0],True)

In [3]:
train_X = pd.read_csv('DataSet/trainX13.csv', header=None)
train_Y = pd.read_csv('DataSet/trainY13.csv', header=None)

trainY = train_Y.to_numpy()
trainX = train_X.to_numpy()
trainX = np.expand_dims(trainX,axis=2)

In [5]:
def poolingModel():

    input_1 = keras.Input(shape = (6000,1))
    
    max_pooling1d_1 = layers.MaxPooling1D(pool_size = 2,strides = 2, padding = 'same')(input_1)
    
    model = keras.Model(inputs = input_1, outputs = max_pooling1d_1)

In [7]:

model = poolingModel()

model.summary()

AttributeError: 'NoneType' object has no attribute 'summary'

In [20]:
#bac = trainX[0][None][:,:,None]
trainX_tensor =  tf.convert_to_tensor(trainX)
output = tf.nn.max_pool1d(trainX_tensor, 2, 2, padding='VALID')

In [21]:
output[0]

<tf.Tensor: shape=(3000, 1), dtype=float64, numpy=
array([[11.5],
       [11.8],
       [ 5. ],
       ...,
       [ 3.1],
       [ 3.2],
       [ 3.1]])>

In [23]:
trainX_tensor

<tf.Tensor: shape=(1680, 6000, 1), dtype=float64, numpy=
array([[[ 8.1],
        [11.5],
        [ 5. ],
        ...,
        [ 3.2],
        [ 3.1],
        [ 3. ]],

       [[ 6.2],
        [ 5.5],
        [ 5.3],
        ...,
        [ 3.2],
        [ 3.1],
        [ 3.2]],

       [[11.4],
        [ 5. ],
        [ 8.3],
        ...,
        [ 5. ],
        [ 5.5],
        [ 5.8]],

       ...,

       [[ 6. ],
        [ 5.3],
        [ 6.6],
        ...,
        [ 3.2],
        [ 3.2],
        [ 3.2]],

       [[ 7.2],
        [ 6.4],
        [ 5.7],
        ...,
        [ 3.2],
        [ 3.2],
        [ 3.2]],

       [[ 5.9],
        [ 5.9],
        [ 7.9],
        ...,
        [ 2.8],
        [ 2.8],
        [ 2.9]]])>